### ISSUE TITLE
Ausdruck seltsam / PDF Version möglich?

### ISSUE THREAD

**Issue by Kebap** [empeiria/keeptalkinggame-german#6]
Hallo, ich möchte gerne die Seiten ausdrucken, aber es sieht dann leider anders aus als im Browser. Das Layout ist verändert, die Hintergrundgrafik fehlt, andere Schriftarten, usw. Wäre es möglich, eine PDF Version zum Download anzubieten? Danke!

**Comment by joerglohrer** [comment]
Gerade mal ein PDF angelegt:
http://empeiria.github.io/keeptalkinggame-german/pdf/German%20Fan-Translation%20Keep%20Talking%20and%20Nobody%20Explodes%20V1R3%20.pdf
Klappt's damit, @Kebap ?

**Comment by Kebap** [comment]
Danke @empeiria - Damit sind Layout und Schriftarten repariert. Nur die Hintergrundgrafik fehlt noch im Vergleich zur Browser-Version. Ist aber trotzdem deutlich besser, damit werden wir arbeiten können! :)

**Comment by Kebap** [comment]
Auf Seite 13 (komplizierte Kabel) fehlt anscheinend das Diagramm? Ich habe auch einzelne Tippfehler gefunden, aber die sammel ich noch eine Weile und schreibe dann hier gemeinsam rein.

**Comment by joerglohrer** [comment]
@Kebap Seite 13 ist repariert und auch die Legende zum Diagramm übersetzt (svg aktualisiert).
Bin gespannt auf die Tippfehlkorrekturen... Danke für deine Unterstützung!

**Comment by joerglohrer** [comment]
Handbuch PDF aktualisiert mit Hintergrundgrafiken: 
http://empeiria.github.io/keeptalkinggame-german/pdf/German%20Fan-Translation%20Keep%20Talking%20and%20Nobody%20Explodes%20V1R3%20.pdf
@Kebap

**Comment by Kebap** [comment]
Auf Seite 13 steht "übber", ansonsten finde ich in der neuen Version keine mehr. :)

**Comment by joerglohrer** [comment]
"übber" -> über
korrigiert.
